// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTP0M12tJjsuyVo-xUMYU6Ab59rz4x2kk',
    appId: '1:950871391773:web:a28bf110437e0bf25210f4',
    messagingSenderId: '950871391773',
    projectId: 'flutter01-74aed',
    authDomain: 'flutter01-74aed.firebaseapp.com',
    storageBucket: 'flutter01-74aed.firebasestorage.app',
    measurementId: 'G-FXT5DZXQ3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGOfV_j1t3xPtxDLV6JnznTlkFYXSpKo0',
    appId: '1:950871391773:android:6c6a8ad732e6731b5210f4',
    messagingSenderId: '950871391773',
    projectId: 'flutter01-74aed',
    storageBucket: 'flutter01-74aed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIbNges-btOIDEIm3nplOkz8vqx0w_nxo',
    appId: '1:950871391773:ios:0b36606f5963dd015210f4',
    messagingSenderId: '950871391773',
    projectId: 'flutter01-74aed',
    storageBucket: 'flutter01-74aed.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

}